import { Injectable } from '@nestjs/common';
import axios, { AxiosInstance, AxiosError, AxiosRequestConfig } from 'axios';
import { FravegaConfig } from '../Config/FravegaConfig';
import { FravegaHttpError } from './error/FravegaHttpError';
import { Logger } from 'src/core/drivers/logger/Logger';

const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

@Injectable()
export class FravegaHttpClient {
  private readonly client: AxiosInstance;
  private readonly MAX_RETRIES = 3;

  constructor(private readonly config: FravegaConfig) {
    this.client = axios.create({
      baseURL: config.baseUrl,
      timeout: 6000,
      headers: {
        'seller-id': config.sellerId,
        'x-fvg-api-key': config.apiKey,
        'x-fvg-api-token': config.apiToken,
        Accept: 'application/json',
        'Content-Type': 'application/json',
        'User-Agent': process.env.FRAVEGA_USER_AGENT ?? 'marketplace-api/1.0'
      }
    });
  }

  /* ========================== GET ========================== */

  async get<T>(url: string, config?: AxiosRequestConfig): Promise<T> {
    return this.requestWithRetry<T>(() => this.client.get<T>(url, config), 'GET', url);
  }

  /* ========================== POST ========================= */

  async post<T>(url: string, body: any, config?: AxiosRequestConfig): Promise<T> {
    return this.requestWithRetry<T>(() => this.client.post<T>(url, body, config), 'POST', url);
  }

  /* ========================== PUT ========================== */

  async put<T>(url: string, body: any, config?: AxiosRequestConfig): Promise<T> {
    return this.requestWithRetry<T>(() => this.client.put<T>(url, body, config), 'PUT', url);
  }

  /* ========================== PATCH ========================== */

  async patch<T>(url: string, body?: any, config?: AxiosRequestConfig): Promise<T> {
    return this.requestWithRetry<T>(() => this.client.patch<T>(url, body, config), 'PATCH', url);
  }

  /* ===================== CORE RETRY ======================== */

  private async requestWithRetry<T>(
    fn: () => Promise<{ data: T }>,
    method: 'GET' | 'POST' | 'PUT' | 'PATCH',
    url: string
  ): Promise<T> {
    const baseURL = this.client.defaults.baseURL ?? '';

    for (let attempt = 1; attempt <= this.MAX_RETRIES; attempt++) {
      try {
        const response = await fn();
        return response.data;
      } catch (error) {
        const err = error as AxiosError;
        const status = err.response?.status;

        /* TIMEOUT */
        if (err.code === 'ECONNABORTED') {
          if (attempt < this.MAX_RETRIES) {
            await sleep(attempt * 600);
            continue;
          }

          throw new FravegaHttpError(null, null, 'TIMEOUT', `[FRAVEGA ${method}] ${baseURL + url} → TIMEOUT`);
        }

        /* RATE LIMIT */
        if (status === 429) {
          if (attempt < this.MAX_RETRIES) {
            await sleep(attempt * 1000);
            continue;
          }

          throw new FravegaHttpError(
            status,
            err.response?.data,
            'RATE_LIMIT',
            `[FRAVEGA ${method}] ${baseURL + url} → RATE LIMIT`
          );
        }

        if (status === 403 && this.isCloudFrontBlocked(err.response?.data)) {
          const blockedResponse = this.sanitizeCloudFrontResponse(err.response?.data);

          Logger.warn(
            `[FRAVEGA ${method}] cloudfront-blocked ${JSON.stringify({
              url: baseURL + url,
              requestId: blockedResponse.requestId
            })}`
          );

          throw new FravegaHttpError(
            status,
            blockedResponse,
            'CLOUDFRONT_BLOCKED',
            `[FRAVEGA ${method}] ${baseURL + url} → CLOUDFRONT_BLOCKED`
          );
        }

        /* SERVER */
        if (status && status >= 500) {
          throw new FravegaHttpError(
            status,
            err.response?.data,
            'SERVER',
            `[FRAVEGA ${method}] ${baseURL + url} → ${status}`
          );
        }

        /* UNKNOWN (esto es el que estás viendo ahora) */
        throw new FravegaHttpError(
          status ?? null,
          err.response?.data ?? err.message,
          'UNKNOWN',
          `[FRAVEGA ${method}] ${baseURL + url} → ${err.message}`
        );
      }
    }

    throw new FravegaHttpError(null, null, 'UNKNOWN', `[FRAVEGA ${method}] ${baseURL + url} → UNKNOWN`);
  }

  private isCloudFrontBlocked(data: unknown): boolean {
    return typeof data === 'string' && data.includes('Generated by cloudfront') && data.includes('Request blocked');
  }

  private sanitizeCloudFrontResponse(data: unknown): { message: string; requestId: string | null } {
    const html = typeof data === 'string' ? data : '';
    const requestId = html.match(/Request ID:\s*([^\s<]+)/)?.[1] ?? null;

    return {
      message: 'Request blocked by CloudFront before reaching Fravega Seller Center',
      requestId
    };
  }
}
